//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NDIzOTk1NzF9.uDQvsqtlvoA-RAQCR69laJE0hAMrn13nqN7vLer9pwM

# POST http://localhost:3000/create-blog
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NDIzOTk1NzF9.uDQvsqtlvoA-RAQCR69laJE0hAMrn13nqN7vLer9pwM

# {

#   "title": "My Blog",
#   "des": "This is a description",
#   "banner": "https://example.com/image-url",
#   "tags": ["blog", "coding"],
#   "content": { "blocks": [1,2] },
#   "draft": false
# }

# POST http://localhost:3000/signup
# Content-Type: application/json

# TEST: Signup with LGD location fields for customer_id
# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#   "first_name": "Amit",
#   "last_name": "Sharma",
#   "email": "amit.sharma@example.com",
#   "password": "Amit@1234567890",
#   "mobile_number": "+919876543210",
#   "country": "India",
#   "state": "JAMMU AND KASHMIR",
#   "district": "KUPWARA",
#   "block": "Hayhama",
#   "village": "Zangli Kashera"
# }
# # Signup - triggers OTP to email and logs OTP for mobile
# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#   "first_name": "Uday Raj",
#   "last_name": "Sahai",
#   "email": "udayrajsahai@gmail.com",
#   "password": "Uday@React3306!",
#   "mobile_number": "+919899724284",
#   "country": "India",
#   "state": "DELHI",
#   "district": "SOUTH WEST",
#   "block": "",
#   "village": "Dichaon Kalan"
# }

# GET http://localhost:3000/latest-blogs

# GET http://localhost:3000/trending-blogs

# POST http://localhost:3000/search-blogs
# Content-Type: application/json

# {
#     "tag": "programming"
# }

# POST http://localhost:3000/search-users
# Content-Type: application/json

# {
#     "query": "him"
# }


# POST http://localhost:3000/get-profile
# Content-Type: application/json

# {
#     "username": "himanshu123"
# }

# POST http://localhost:3000/get-blog
# Content-Type: application/json

# {
#     "blog_id": "Smart-Saving-Tips-for-Millennials-and-Gen-ZVzEmkkVQAjmLo_3yhGtXn"
# }

# POST http://localhost:3000/handle-like
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NDIzOTk1NzF9.uDQvsqtlvoA-RAQCR69laJE0hAMrn13nqN7vLer9pwM

# {
#     "blog_id": "React-Hooks-ExplainedL6NzuLuqFvRm8Lrcv8zDK",
#     "isLiked": true
    
# }

# GET http://localhost:3000/notifications
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NDIzOTk1NzF9.uDQvsqtlvoA-RAQCR69laJE0hAMrn13nqN7vLer9pwM

# POST http://localhost:3000/add-comment
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NDIzOTk1NzF9.uDQvsqtlvoA-RAQCR69laJE0hAMrn13nqN7vLer9pwM

# {
#     "blog_id": "Want-to-grow-your-followers-without-spending-on-ads-Here-s-how-RrbLuJ7dmZWUMg_M3fXHT",
#     "comment": "Very helpful !!!! I was struggling with this but thanks to you i got the solution now . Thanks a ton !!!!!"
# }

# POST http://localhost:3000/add-comment
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NDIzOTk1NzF9.uDQvsqtlvoA-RAQCR69laJE0hAMrn13nqN7vLer9pwM

# {
#     "blog_id": "Want-to-grow-your-followers-without-spending-on-ads-Here-s-how-RrbLuJ7dmZWUMg_M3fXHT",
#     "comment": "Thanks for sharing your thoughts! I agree completely.",
#     "replying_to": "comment_cIfFCgQGUHKe-hKTWD0DX"
# }

# POST http://localhost:3000/get-blog-comments
# Content-Type: application/json

# {
#   "blog_id": "Want-to-grow-your-followers-without-spending-on-ads-Here-s-how-RrbLuJ7dmZWUMg_M3fXHT"
# }

# DELETE http://localhost:3000/delete-comment
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NDIzOTk1NzF9.uDQvsqtlvoA-RAQCR69laJE0hAMrn13nqN7vLer9pwM

# {
#   "comment_id": "comment_qxaruX5LcQjAkCxWZa3uH"
# }

# GET http://localhost:3000/new-notification
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NDIzOTk1NzF9.uDQvsqtlvoA-RAQCR69laJE0hAMrn13nqN7vLer9pwM

# POST http://localhost:3000/signin
# Content-Type: application/json

# {
#   "email": "pradeep123@yahoo.com",
#   "password": "Pradeep@123456789"
# }


# POST http://localhost:3000/notifications
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiaWF0IjoxNzUwNDkwODgzfQ.hqTO-hrzctN28ilyUfkprIKVR_C5zeEAoEH6uj_cjRw

# {
#   "page": 1,
#   "filter": "all"
# }

# # Verify Email OTP
POST http://localhost:3000/verify-email-otp
Content-Type: application/json

{
  "email": "udayrajsahai@gmail.com",
  "otp": "738105" 
}







